#!/bin/bash

function get-aws-id() {
    aws sts get-caller-identity --query Account --output text

}

function aws-docker-tag() {
    if [ $# -ne 1 ]; then
        echo "Usage: aws-docker-tag <container_name>"
        exit 1
    fi

    AWS_ID=$(get-aws-id)
    docker tag $1:latest "$AWS_ID.dkr.ecr.us-west-2.amazonaws.com/$1:latest"
    docker push "$AWS_ID.dkr.ecr.us-west-2.amazonaws.com/$1:latest"
}

function aws-profile() {
    if [ $# -eq 0 ]; then
        echo "Current AWS_PROFILE: $AWS_PROFILE"
        echo "Possible Profiles:"
        aws configure list-profiles
    else
        export AWS_PROFILE="$1"
        echo "Switched to AWS profile: $AWS_PROFILE"
        aws configure list
    fi
}
