# exec-once = hypridle & waybar &
# exec-once = swaybg -i ~/background.jpg -m fill
# exec-once = systemctl --user start hyprpolkitagent
# exec-once = wl-clip-persist --clipboard regular & clipse -listen
# exec-once = nm-applet --indicator
exec-once = ~/dotfiles/bin/move_displays

exec-once = [workspace 1 silent] alacritty
# start emacs or connect a new frame connected to the existing emacs process
exec-once = [workspace 2 silent] emacsclient -c -n --alternate-editor=""
exec-once = [workspace 3 silent] chromium
