# Default applications
$terminal = alacritty
$fileManager = nautilus --new-window
$browser = brave --new-window --enable-features=UseOzonePlatform --ozone-platform=wayland --force-device-scale-factor=1.0
$music = spotify
$webapp = $browser --app

animations {
  enabled = 0
}
general {
    gaps_in = 0
    gaps_out = 0
    border_size = 0
    layout = master
}

source = ~/dotfiles/.config/hypr/bindings.conf
source = ~/dotfiles/.config/hypr/monitors.conf
source = ~/dotfiles/.config/hypr/autostart.conf
source = ~/dotfiles/.config/hypr/input.conf

input {
    follow_mouse = 0
    mouse_refocus = false
}

windowrule = opacity 1.00, match:class .*
windowrule = render_unfocused on, match:class Chromium
windowrule = render_unfocused on, match:class chromium

env = GDK_SCALE,2

env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Adwaita

misc {
    force_default_wallpaper = 0
    focus_on_activate = true
    disable_hyprland_logo = true
    render_unfocused_fps = 60
}
