#! /bin/sh

sxhkd &
# compton &

# $XDG_CONFIG_HOME/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width   0
# bspc config window_gap   0
bspc config bottom_padding 44

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2' follow=on focus=on
