[user]
name = "lanceberge"
email = "bergeron.lance6@gmail.com"

[revsets]
bookmark-advance-to = "@-"

[ui]
editor = "emacsclient -t"
default-command = "log"
diff-editor = ":builtin"
pager = "less -FRX"
conflict-marker-style = "git"

[git]
fetch = ["origin"]
push = "origin"

[aliases]
ba = ["bookmark advance"]
b = ["bookmark"]
bl = ["bookmark", "list"]
bs = ["bookmark", "set"]
bd = ["bookmark", "delete"]

l = ["log"]
s = ["squash"]
lag = ["log", "-r", "all()"]
d = ["diff"]

dm = ["describe", "-m"]

n = ["new"]
c = ["util", "exec", "--", "sh", "-c", "jj commit -m \"$*\" && jj new && jj bookmark advance", ""]
e = ["edit"]

r = ["rebase"]

ab = ["abandon"]
u = ["undo"]

p = ["git", "push"]
f = ["git", "fetch"]

# [templates]
# commit_trailers = TODO
