[user]
name = "lanceberge"
email = "bergeron.lance6@gmail.com"

[revsets]
bookmark-advance-to = "@-"

[remotes.origin]
auto-track-bookmarks = "*"

[ui]
editor = "emacsclient -t"
default-command = "status"
diff-editor = ":builtin"
pager = "less -FRX"
conflict-marker-style = "git"

[git]
fetch = ["origin"]
push = "origin"

[aliases]
ba = ["bookmark", "advance"]
b = ["bookmark"]
bl = ["bookmark", "list"]
bs = ["bookmark", "set"]
bd = ["bookmark", "delete"]
my_bookmarks = ["bookmark", "list", "-r", "mine()", "--sort", "committer-date-"]

l = ["log"]
la = ["log", "-r", "ancestors(@)"]

s = ["squash"]
si = ["squash", "--ignore-immutable"]

d = ["diff"]
sh = ["show", "@-"]
shr = ["show"]

# modifying commits
n = ["new"]
c = ["util", "exec", "--", "sh", "-c", "jj commit -m \"$*\" && jj bookmark advance", ""]
e = ["edit"]
mr = ["util", "exec", "--", "sh", "-c", "jj describe -r \"$1\" -m \"$2\"", ""]
m = ["describe", "-m"]
a = ["absorb"]
r = ["rebase"]

ab = ["abandon"]
u = ["undo"]

p = ["git", "push"]
f = ["git", "fetch"]

t = ["tag"]
tr = ["tag", "list", "--sort", "author-date-"]

filelog = ["log", "-r", 'files("$1")']
